server:
  port: 9090

spring:
  application:
    name: aura

  web:
    resources:
      static-locations: classpath:/static/   # ✅ colon not equals, no space after classpath
      add-mappings: true                      # ✅ true to ENABLE static serving

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: POOJI

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true