server:
  port: ${PORT:8080}

spring:
  application:
    name: aura

  web:
    resources:
      static-locations: classpath:/static/   # ✅ colon not equals, no space after classpath
      add-mappings: true                      # ✅ true to ENABLE static serving

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_PUBLIC_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
